ui_pyside6:
	pyside6-uic mainwindow.ui -o ui_mainwindow.py
	pyside6-uic preferences.ui -o ui_preferences.py
	pyside6-uic snakemake.ui -o ui_snakemake.py
	pyside6-uic help.ui -o ui_help.py

ui_pyqt5:
	pyuic5 mainwindow.ui -o ui_mainwindow.py
	pyuic5 preferences.ui -o ui_preferences.py
	pyuic5 snakemake.ui -o ui_snakemake.py
	pyuic5 help.ui -o ui_help.py
