name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore: []
  schedule:
    - cron: '0 0 * * SUN'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.12
    - name: Setup ubuntu
      run: |
        sudo apt install xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
        sudo apt install graphviz
    - name: Install dependencies
      run: |
        pip install .[testing]
        pip install sequana_fastqc
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude sequanix/ui/
    - name: Test with pytest
      run: |
        #sudo Xvfb :1 -screen 0 1024x768x24 </dev/null &
        #export DISPLAY=":1"
        pytest --cov-report term-missing --cov=sequanix


    - name: coveralls
      run: |
        pip install coveralls
        coveralls --service=github
      env:
          GITHUB_TOKEN: ${{ github.token }}
